import { Tool, ToolCategory, CategoryInfo } from '@/types/tool'

// Category Information
export const categories: CategoryInfo[] = [
  {
    id: ToolCategory.FILE,
    name: 'File Tools',
    description: 'PDF converters, mergers, compressors and more',
    icon: 'FileText',
    color: '#8b5cf6',
  },
  {
    id: ToolCategory.IMAGE,
    name: 'Image Tools',
    description: 'Resize, compress, convert and edit images',
    icon: 'Image',
    color: '#06b6d4',
  },
  {
    id: ToolCategory.TEXT,
    name: 'Text Tools',
    description: 'Text manipulation and conversion utilities',
    icon: 'Type',
    color: '#a78bfa',
  },
  {
    id: ToolCategory.CODE,
    name: 'Code Tools',
    description: 'Formatters, minifiers and code utilities',
    icon: 'Code',
    color: '#10b981',
  },
  {
    id: ToolCategory.SEO,
    name: 'SEO Tools',
    description: 'Meta tags, schema markup and SEO utilities',
    icon: 'TrendingUp',
    color: '#f59e0b',
  },
  {
    id: ToolCategory.VIDEO,
    name: 'Video Tools',
    description: 'Video converters, compressors and editors',
    icon: 'Video',
    color: '#ef4444',
  },
  {
    id: ToolCategory.AUDIO,
    name: 'Audio Tools',
    description: 'Audio converters, trimmers and processors',
    icon: 'Music',
    color: '#ec4899',
  },
  {
    id: ToolCategory.SECURITY,
    name: 'Security Tools',
    description: 'Password generators, encryption and hashing',
    icon: 'Shield',
    color: '#6366f1',
  },
]

// All 115 Tools
export const allTools: Tool[] = [
  // FILE TOOLS (15)
  {
    id: 1,
    slug: 'pdf-to-word-converter',
    name: 'PDF to Word Converter',
    shortDescription: 'Convert PDF files to Word documents',
    fullDescription: 'Free online PDF to Word converter. Convert PDF files to editable Word documents instantly. No login required. Fast, secure, and 100% free forever.',
    category: ToolCategory.FILE,
    tags: ['pdf', 'word', 'docx', 'converter', 'document'],
    icon: 'FileText',
    featured: true,
    relatedTools: ['pdf-to-jpg-converter', 'word-to-pdf-converter', 'pdf-merger', 'pdf-splitter'],
    componentName: 'PdfToWordTool',
    metaTitle: 'PDF to Word Converter - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online PDF to Word converter. Convert PDF files to editable Word documents instantly. No login required. Fast, secure, and 100% free forever.',
    metaKeywords: ['pdf to word', 'pdf converter', 'pdf to docx', 'convert pdf'],
    howToUse: [
      'Upload your PDF file',
      'Click "Convert to Word"',
      'Wait for processing',
      'Download your Word document',
    ],
    inputType: 'file',
    outputType: 'file',
    maxFileSize: 50,
    acceptedFormats: ['application/pdf'],
  },
  {
    id: 2,
    slug: 'pdf-to-jpg-converter',
    name: 'PDF to JPG Converter',
    shortDescription: 'Convert PDF pages to JPG images',
    fullDescription: 'Free online PDF to JPG converter. Convert PDF pages to high-quality JPG images. No login required. Fast, secure, and 100% free forever.',
    category: ToolCategory.FILE,
    tags: ['pdf', 'jpg', 'image', 'converter'],
    icon: 'FileImage',
    featured: false,
    relatedTools: ['pdf-to-word-converter', 'jpg-to-pdf-converter', 'image-compressor'],
    componentName: 'PdfToJpgTool',
    metaTitle: 'PDF to JPG Converter - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online PDF to JPG converter. Convert PDF pages to high-quality JPG images instantly.',
    metaKeywords: ['pdf to jpg', 'pdf to image', 'convert pdf to jpeg'],
    howToUse: [
      'Upload your PDF file',
      'Select pages to convert',
      'Click "Convert to JPG"',
      'Download your images',
    ],
    inputType: 'file',
    outputType: 'file',
    maxFileSize: 50,
    acceptedFormats: ['application/pdf'],
  },
  {
    id: 3,
    slug: 'jpg-to-pdf-converter',
    name: 'JPG to PDF Converter',
    shortDescription: 'Convert JPG images to PDF documents',
    fullDescription: 'Free online JPG to PDF converter. Convert multiple JPG images into a single PDF document. No login required.',
    category: ToolCategory.FILE,
    tags: ['jpg', 'pdf', 'image', 'converter'],
    icon: 'FileImage',
    featured: true,
    relatedTools: ['pdf-to-jpg-converter', 'image-compressor', 'pdf-merger'],
    componentName: 'JpgToPdfTool',
    metaTitle: 'JPG to PDF Converter - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online JPG to PDF converter. Convert multiple JPG images into a single PDF document instantly.',
    metaKeywords: ['jpg to pdf', 'image to pdf', 'convert jpg to pdf'],
    howToUse: [
      'Upload your JPG images',
      'Arrange images in order',
      'Click "Convert to PDF"',
      'Download your PDF',
    ],
    inputType: 'file',
    outputType: 'file',
    maxFileSize: 10,
    acceptedFormats: ['image/jpeg', 'image/jpg'],
  },
  {
    id: 4,
    slug: 'word-to-pdf-converter',
    name: 'Word to PDF Converter',
    shortDescription: 'Convert Word documents to PDF',
    fullDescription: 'Free online Word to PDF converter. Convert DOCX files to PDF format instantly. No login required.',
    category: ToolCategory.FILE,
    tags: ['word', 'pdf', 'docx', 'converter'],
    icon: 'FileText',
    featured: false,
    relatedTools: ['pdf-to-word-converter', 'excel-to-pdf-converter'],
    componentName: 'WordToPdfTool',
    metaTitle: 'Word to PDF Converter - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online Word to PDF converter. Convert DOCX files to PDF format instantly.',
    metaKeywords: ['word to pdf', 'docx to pdf', 'convert word to pdf'],
    howToUse: [
      'Upload your Word document',
      'Click "Convert to PDF"',
      'Wait for processing',
      'Download your PDF',
    ],
    inputType: 'file',
    outputType: 'file',
    maxFileSize: 50,
    acceptedFormats: ['application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
  },
  {
    id: 5,
    slug: 'excel-to-pdf-converter',
    name: 'Excel to PDF Converter',
    shortDescription: 'Convert Excel spreadsheets to PDF',
    fullDescription: 'Free online Excel to PDF converter. Convert XLSX files to PDF format instantly. No login required.',
    category: ToolCategory.FILE,
    tags: ['excel', 'pdf', 'xlsx', 'converter'],
    icon: 'FileSpreadsheet',
    featured: false,
    relatedTools: ['word-to-pdf-converter', 'pdf-merger'],
    componentName: 'ExcelToPdfTool',
    metaTitle: 'Excel to PDF Converter - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online Excel to PDF converter. Convert XLSX files to PDF format instantly.',
    metaKeywords: ['excel to pdf', 'xlsx to pdf', 'convert excel to pdf'],
    howToUse: [
      'Upload your Excel file',
      'Click "Convert to PDF"',
      'Wait for processing',
      'Download your PDF',
    ],
    inputType: 'file',
    outputType: 'file',
    maxFileSize: 50,
    acceptedFormats: ['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'],
  },
  {
    id: 6,
    slug: 'pdf-merger',
    name: 'PDF Merger',
    shortDescription: 'Merge multiple PDF files into one',
    fullDescription: 'Free online PDF merger. Combine multiple PDF files into a single document. No login required. Fast, secure, and 100% free forever.',
    category: ToolCategory.FILE,
    tags: ['pdf', 'merge', 'combine', 'join'],
    icon: 'FilePlus',
    featured: true,
    relatedTools: ['pdf-splitter', 'pdf-compressor', 'pdf-page-extractor'],
    componentName: 'PdfMergerTool',
    metaTitle: 'PDF Merger - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online PDF merger. Combine multiple PDF files into a single document instantly.',
    metaKeywords: ['pdf merger', 'merge pdf', 'combine pdf', 'join pdf files'],
    howToUse: [
      'Upload multiple PDF files',
      'Arrange PDFs in desired order',
      'Click "Merge PDFs"',
      'Download merged PDF',
    ],
    inputType: 'file',
    outputType: 'file',
    maxFileSize: 50,
    acceptedFormats: ['application/pdf'],
  },
  {
    id: 7,
    slug: 'pdf-splitter',
    name: 'PDF Splitter',
    shortDescription: 'Split PDF into multiple files',
    fullDescription: 'Free online PDF splitter. Split large PDF files into smaller documents. No login required.',
    category: ToolCategory.FILE,
    tags: ['pdf', 'split', 'divide', 'separate'],
    icon: 'FileMinus',
    featured: false,
    relatedTools: ['pdf-merger', 'pdf-page-extractor', 'pdf-compressor'],
    componentName: 'PdfSplitterTool',
    metaTitle: 'PDF Splitter - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online PDF splitter. Split large PDF files into smaller documents instantly.',
    metaKeywords: ['pdf splitter', 'split pdf', 'divide pdf', 'separate pdf pages'],
    howToUse: [
      'Upload your PDF file',
      'Choose split method (by pages or size)',
      'Click "Split PDF"',
      'Download split files',
    ],
    inputType: 'file',
    outputType: 'file',
    maxFileSize: 50,
    acceptedFormats: ['application/pdf'],
  },
  {
    id: 8,
    slug: 'pdf-compressor',
    name: 'PDF Compressor',
    shortDescription: 'Compress PDF files to reduce size',
    fullDescription: 'Free online PDF compressor. Reduce PDF file size while maintaining quality. No login required.',
    category: ToolCategory.FILE,
    tags: ['pdf', 'compress', 'reduce', 'optimize'],
    icon: 'FileArchive',
    featured: true,
    relatedTools: ['pdf-merger', 'pdf-splitter', 'image-compressor'],
    componentName: 'PdfCompressorTool',
    metaTitle: 'PDF Compressor - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online PDF compressor. Reduce PDF file size while maintaining quality instantly.',
    metaKeywords: ['pdf compressor', 'compress pdf', 'reduce pdf size', 'optimize pdf'],
    howToUse: [
      'Upload your PDF file',
      'Select compression level',
      'Click "Compress PDF"',
      'Download compressed file',
    ],
    inputType: 'file',
    outputType: 'file',
    maxFileSize: 50,
    acceptedFormats: ['application/pdf'],
  },
  {
    id: 9,
    slug: 'pdf-password-remover',
    name: 'PDF Password Remover',
    shortDescription: 'Remove password protection from PDF',
    fullDescription: 'Free online PDF password remover. Remove password protection from PDF files. No login required.',
    category: ToolCategory.FILE,
    tags: ['pdf', 'password', 'unlock', 'decrypt'],
    icon: 'Unlock',
    featured: false,
    relatedTools: ['pdf-password-protector', 'pdf-merger'],
    componentName: 'PdfPasswordRemoverTool',
    metaTitle: 'PDF Password Remover - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online PDF password remover. Remove password protection from PDF files instantly.',
    metaKeywords: ['pdf password remover', 'unlock pdf', 'remove pdf password'],
    howToUse: [
      'Upload password-protected PDF',
      'Enter the current password',
      'Click "Remove Password"',
      'Download unlocked PDF',
    ],
    inputType: 'file',
    outputType: 'file',
    maxFileSize: 50,
    acceptedFormats: ['application/pdf'],
  },
  {
    id: 10,
    slug: 'pdf-password-protector',
    name: 'PDF Password Protector',
    shortDescription: 'Add password protection to PDF',
    fullDescription: 'Free online PDF password protector. Secure your PDF files with password protection. No login required.',
    category: ToolCategory.FILE,
    tags: ['pdf', 'password', 'protect', 'encrypt', 'secure'],
    icon: 'Lock',
    featured: false,
    relatedTools: ['pdf-password-remover', 'aes-encryptor'],
    componentName: 'PdfPasswordProtectorTool',
    metaTitle: 'PDF Password Protector - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online PDF password protector. Secure your PDF files with password protection instantly.',
    metaKeywords: ['pdf password protector', 'protect pdf', 'encrypt pdf', 'secure pdf'],
    howToUse: [
      'Upload your PDF file',
      'Enter a strong password',
      'Click "Protect PDF"',
      'Download protected PDF',
    ],
    inputType: 'file',
    outputType: 'file',
    maxFileSize: 50,
    acceptedFormats: ['application/pdf'],
  },
  {
    id: 11,
    slug: 'pdf-page-rotator',
    name: 'PDF Page Rotator',
    shortDescription: 'Rotate PDF pages',
    fullDescription: 'Free online PDF page rotator. Rotate PDF pages to correct orientation. No login required.',
    category: ToolCategory.FILE,
    tags: ['pdf', 'rotate', 'orientation'],
    icon: 'RotateCw',
    featured: false,
    relatedTools: ['pdf-splitter', 'pdf-page-extractor', 'pdf-merger'],
    componentName: 'PdfPageRotatorTool',
    metaTitle: 'PDF Page Rotator - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online PDF page rotator. Rotate PDF pages to correct orientation instantly.',
    metaKeywords: ['pdf rotator', 'rotate pdf', 'pdf orientation'],
    howToUse: [
      'Upload your PDF file',
      'Select pages to rotate',
      'Choose rotation angle',
      'Download rotated PDF',
    ],
    inputType: 'file',
    outputType: 'file',
    maxFileSize: 50,
    acceptedFormats: ['application/pdf'],
  },
  {
    id: 12,
    slug: 'pdf-page-extractor',
    name: 'PDF Page Extractor',
    shortDescription: 'Extract specific pages from PDF',
    fullDescription: 'Free online PDF page extractor. Extract specific pages from PDF documents. No login required.',
    category: ToolCategory.FILE,
    tags: ['pdf', 'extract', 'pages'],
    icon: 'FileOutput',
    featured: false,
    relatedTools: ['pdf-splitter', 'pdf-merger', 'pdf-page-rotator'],
    componentName: 'PdfPageExtractorTool',
    metaTitle: 'PDF Page Extractor - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online PDF page extractor. Extract specific pages from PDF documents instantly.',
    metaKeywords: ['pdf page extractor', 'extract pdf pages', 'pdf pages'],
    howToUse: [
      'Upload your PDF file',
      'Select pages to extract',
      'Click "Extract Pages"',
      'Download extracted PDF',
    ],
    inputType: 'file',
    outputType: 'file',
    maxFileSize: 50,
    acceptedFormats: ['application/pdf'],
  },
  {
    id: 13,
    slug: 'file-format-converter',
    name: 'File Format Converter',
    shortDescription: 'Convert between various file formats',
    fullDescription: 'Free online file format converter. Convert between various document and file formats. No login required.',
    category: ToolCategory.FILE,
    tags: ['converter', 'file', 'format'],
    icon: 'RefreshCw',
    featured: false,
    relatedTools: ['pdf-to-word-converter', 'image-converter'],
    componentName: 'FileFormatConverterTool',
    metaTitle: 'File Format Converter - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online file format converter. Convert between various file formats instantly.',
    metaKeywords: ['file converter', 'format converter', 'convert files'],
    howToUse: [
      'Upload your file',
      'Select target format',
      'Click "Convert"',
      'Download converted file',
    ],
    inputType: 'file',
    outputType: 'file',
    maxFileSize: 50,
  },
  {
    id: 14,
    slug: 'zip-file-extractor',
    name: 'ZIP File Extractor',
    shortDescription: 'Extract files from ZIP archives',
    fullDescription: 'Free online ZIP file extractor. Extract and decompress ZIP archives in your browser. No login required.',
    category: ToolCategory.FILE,
    tags: ['zip', 'extract', 'decompress', 'unzip'],
    icon: 'FolderArchive',
    featured: false,
    relatedTools: ['base64-file-encoder'],
    componentName: 'ZipExtractorTool',
    metaTitle: 'ZIP File Extractor - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online ZIP file extractor. Extract and decompress ZIP archives in your browser.',
    metaKeywords: ['zip extractor', 'unzip', 'extract zip', 'decompress zip'],
    howToUse: [
      'Upload your ZIP file',
      'Click "Extract"',
      'View extracted files',
      'Download individual files',
    ],
    inputType: 'file',
    outputType: 'file',
    maxFileSize: 100,
    acceptedFormats: ['application/zip', 'application/x-zip-compressed'],
  },
  {
    id: 15,
    slug: 'base64-file-encoder',
    name: 'Base64 File Encoder/Decoder',
    shortDescription: 'Encode and decode files to Base64',
    fullDescription: 'Free online Base64 file encoder and decoder. Convert files to Base64 strings and back. No login required.',
    category: ToolCategory.FILE,
    tags: ['base64', 'encode', 'decode', 'file'],
    icon: 'FileCode',
    featured: false,
    relatedTools: ['base64-encoder', 'image-to-base64'],
    componentName: 'Base64FileEncoderTool',
    metaTitle: 'Base64 File Encoder - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online Base64 file encoder and decoder. Convert files to Base64 strings instantly.',
    metaKeywords: ['base64 encoder', 'base64 decoder', 'file to base64'],
    howToUse: [
      'Upload your file',
      'Choose encode or decode',
      'Click "Process"',
      'Copy or download result',
    ],
    inputType: 'file',
    outputType: 'both',
    maxFileSize: 10,
  },

  // IMAGE TOOLS (18)
  {
    id: 16,
    slug: 'image-resizer',
    name: 'Image Resizer',
    shortDescription: 'Resize images to custom dimensions',
    fullDescription: 'Free online image resizer. Resize images to custom dimensions while maintaining quality. No login required.',
    category: ToolCategory.IMAGE,
    tags: ['image', 'resize', 'dimensions', 'scale'],
    icon: 'Maximize',
    featured: true,
    relatedTools: ['image-compressor', 'image-cropper', 'image-rotator'],
    componentName: 'ImageResizerTool',
    metaTitle: 'Image Resizer - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online image resizer. Resize images to custom dimensions instantly.',
    metaKeywords: ['image resizer', 'resize image', 'image dimensions', 'scale image'],
    howToUse: [
      'Upload your image',
      'Enter target width and height',
      'Choose quality settings',
      'Download resized image',
    ],
    inputType: 'file',
    outputType: 'file',
    maxFileSize: 10,
    acceptedFormats: ['image/*'],
  },
  {
    id: 17,
    slug: 'image-compressor',
    name: 'Image Compressor',
    shortDescription: 'Compress images to reduce file size',
    fullDescription: 'Free online image compressor. Reduce image file size while maintaining quality. No login required.',
    category: ToolCategory.IMAGE,
    tags: ['image', 'compress', 'optimize', 'reduce'],
    icon: 'Minimize',
    featured: true,
    relatedTools: ['image-resizer', 'webp-converter', 'pdf-compressor'],
    componentName: 'ImageCompressorTool',
    metaTitle: 'Image Compressor - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online image compressor. Reduce image file size while maintaining quality instantly.',
    metaKeywords: ['image compressor', 'compress image', 'optimize image', 'reduce image size'],
    howToUse: [
      'Upload your image',
      'Select compression level',
      'Click "Compress"',
      'Download compressed image',
    ],
    inputType: 'file',
    outputType: 'file',
    maxFileSize: 10,
    acceptedFormats: ['image/*'],
  },
  {
    id: 18,
    slug: 'image-cropper',
    name: 'Image Cropper',
    shortDescription: 'Crop images to custom size',
    fullDescription: 'Free online image cropper. Crop images to custom size and aspect ratio. No login required.',
    category: ToolCategory.IMAGE,
    tags: ['image', 'crop', 'cut', 'trim'],
    icon: 'Crop',
    featured: false,
    relatedTools: ['image-resizer', 'image-rotator', 'photo-editor'],
    componentName: 'ImageCropperTool',
    metaTitle: 'Image Cropper - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online image cropper. Crop images to custom size and aspect ratio instantly.',
    metaKeywords: ['image cropper', 'crop image', 'cut image', 'trim image'],
    howToUse: [
      'Upload your image',
      'Select crop area',
      'Adjust crop dimensions',
      'Download cropped image',
    ],
    inputType: 'file',
    outputType: 'file',
    maxFileSize: 10,
    acceptedFormats: ['image/*'],
  },
  {
    id: 19,
    slug: 'jpg-to-png-converter',
    name: 'JPG to PNG Converter',
    shortDescription: 'Convert JPG images to PNG format',
    fullDescription: 'Free online JPG to PNG converter. Convert JPEG images to PNG format with transparency support.',
    category: ToolCategory.IMAGE,
    tags: ['jpg', 'png', 'converter', 'image'],
    icon: 'Image',
    featured: false,
    relatedTools: ['png-to-jpg-converter', 'webp-converter', 'image-compressor'],
    componentName: 'JpgToPngTool',
    metaTitle: 'JPG to PNG Converter - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online JPG to PNG converter. Convert JPEG images to PNG format instantly.',
    metaKeywords: ['jpg to png', 'jpeg to png', 'convert jpg to png'],
    howToUse: [
      'Upload JPG image',
      'Click "Convert to PNG"',
      'Wait for processing',
      'Download PNG image',
    ],
    inputType: 'file',
    outputType: 'file',
    maxFileSize: 10,
    acceptedFormats: ['image/jpeg', 'image/jpg'],
  },
  {
    id: 20,
    slug: 'png-to-jpg-converter',
    name: 'PNG to JPG Converter',
    shortDescription: 'Convert PNG images to JPG format',
    fullDescription: 'Free online PNG to JPG converter. Convert PNG images to JPEG format for smaller file sizes.',
    category: ToolCategory.IMAGE,
    tags: ['png', 'jpg', 'converter', 'image'],
    icon: 'Image',
    featured: false,
    relatedTools: ['jpg-to-png-converter', 'webp-converter', 'image-compressor'],
    componentName: 'PngToJpgTool',
    metaTitle: 'PNG to JPG Converter - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online PNG to JPG converter. Convert PNG images to JPEG format instantly.',
    metaKeywords: ['png to jpg', 'png to jpeg', 'convert png to jpg'],
    howToUse: [
      'Upload PNG image',
      'Click "Convert to JPG"',
      'Wait for processing',
      'Download JPG image',
    ],
    inputType: 'file',
    outputType: 'file',
    maxFileSize: 10,
    acceptedFormats: ['image/png'],
  },
  {
    id: 21,
    slug: 'webp-converter',
    name: 'WebP Converter',
    shortDescription: 'Convert images to WebP format',
    fullDescription: 'Free online WebP converter. Convert images to modern WebP format for better compression.',
    category: ToolCategory.IMAGE,
    tags: ['webp', 'converter', 'image', 'optimize'],
    icon: 'Image',
    featured: true,
    relatedTools: ['image-compressor', 'jpg-to-png-converter', 'png-to-jpg-converter'],
    componentName: 'WebpConverterTool',
    metaTitle: 'WebP Converter - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online WebP converter. Convert images to WebP format for better compression.',
    metaKeywords: ['webp converter', 'convert to webp', 'image to webp'],
    howToUse: [
      'Upload your image',
      'Click "Convert to WebP"',
      'Adjust quality settings',
      'Download WebP image',
    ],
    inputType: 'file',
    outputType: 'file',
    maxFileSize: 10,
    acceptedFormats: ['image/*'],
  },
  {
    id: 22,
    slug: 'image-to-base64',
    name: 'Image to Base64',
    shortDescription: 'Convert images to Base64 strings',
    fullDescription: 'Free online image to Base64 converter. Convert images to Base64 encoded strings.',
    category: ToolCategory.IMAGE,
    tags: ['image', 'base64', 'encode', 'data-url'],
    icon: 'FileCode',
    featured: false,
    relatedTools: ['base64-to-image', 'base64-encoder'],
    componentName: 'ImageToBase64Tool',
    metaTitle: 'Image to Base64 - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online image to Base64 converter. Convert images to Base64 strings instantly.',
    metaKeywords: ['image to base64', 'base64 image', 'encode image'],
    howToUse: [
      'Upload your image',
      'Click "Convert"',
      'Copy Base64 string',
      'Use in your code',
    ],
    inputType: 'file',
    outputType: 'text',
    maxFileSize: 5,
    acceptedFormats: ['image/*'],
  },
  {
    id: 23,
    slug: 'base64-to-image',
    name: 'Base64 to Image',
    shortDescription: 'Convert Base64 strings to images',
    fullDescription: 'Free online Base64 to image converter. Decode Base64 strings to image files.',
    category: ToolCategory.IMAGE,
    tags: ['base64', 'image', 'decode'],
    icon: 'FileImage',
    featured: false,
    relatedTools: ['image-to-base64', 'base64-encoder'],
    componentName: 'Base64ToImageTool',
    metaTitle: 'Base64 to Image - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online Base64 to image converter. Decode Base64 strings to images instantly.',
    metaKeywords: ['base64 to image', 'decode base64', 'base64 decoder'],
    howToUse: [
      'Paste Base64 string',
      'Click "Convert"',
      'View image preview',
      'Download image',
    ],
    inputType: 'text',
    outputType: 'file',
  },
  {
    id: 24,
    slug: 'image-filter-effects',
    name: 'Image Filter & Effects',
    shortDescription: 'Apply filters and effects to images',
    fullDescription: 'Free online image filter tool. Apply various filters and effects to your images.',
    category: ToolCategory.IMAGE,
    tags: ['image', 'filter', 'effects', 'edit'],
    icon: 'Sparkles',
    featured: false,
    relatedTools: ['photo-editor', 'image-grayscale', 'image-rotator'],
    componentName: 'ImageFilterTool',
    metaTitle: 'Image Filter & Effects - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online image filter tool. Apply various filters and effects to images.',
    metaKeywords: ['image filter', 'image effects', 'photo filter'],
    howToUse: [
      'Upload your image',
      'Select filter or effect',
      'Adjust intensity',
      'Download edited image',
    ],
    inputType: 'file',
    outputType: 'file',
    maxFileSize: 10,
    acceptedFormats: ['image/*'],
  },
  {
    id: 25,
    slug: 'image-rotator',
    name: 'Image Rotator',
    shortDescription: 'Rotate images to any angle',
    fullDescription: 'Free online image rotator. Rotate images to any angle or flip horizontally/vertically.',
    category: ToolCategory.IMAGE,
    tags: ['image', 'rotate', 'flip', 'transform'],
    icon: 'RotateCw',
    featured: false,
    relatedTools: ['image-flipper', 'image-cropper', 'image-resizer'],
    componentName: 'ImageRotatorTool',
    metaTitle: 'Image Rotator - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online image rotator. Rotate images to any angle instantly.',
    metaKeywords: ['image rotator', 'rotate image', 'flip image'],
    howToUse: [
      'Upload your image',
      'Select rotation angle',
      'Click "Rotate"',
      'Download rotated image',
    ],
    inputType: 'file',
    outputType: 'file',
    maxFileSize: 10,
    acceptedFormats: ['image/*'],
  },
  {
    id: 26,
    slug: 'image-flipper',
    name: 'Image Flipper',
    shortDescription: 'Flip images horizontally or vertically',
    fullDescription: 'Free online image flipper. Flip images horizontally or vertically with one click.',
    category: ToolCategory.IMAGE,
    tags: ['image', 'flip', 'mirror', 'transform'],
    icon: 'FlipHorizontal',
    featured: false,
    relatedTools: ['image-rotator', 'image-cropper', 'photo-editor'],
    componentName: 'ImageFlipperTool',
    metaTitle: 'Image Flipper - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online image flipper. Flip images horizontally or vertically instantly.',
    metaKeywords: ['image flipper', 'flip image', 'mirror image'],
    howToUse: [
      'Upload your image',
      'Choose flip direction',
      'Click "Flip"',
      'Download flipped image',
    ],
    inputType: 'file',
    outputType: 'file',
    maxFileSize: 10,
    acceptedFormats: ['image/*'],
  },
  {
    id: 27,
    slug: 'background-remover',
    name: 'Background Remover',
    shortDescription: 'Remove background from images',
    fullDescription: 'Free online background remover. Remove background from images automatically.',
    category: ToolCategory.IMAGE,
    tags: ['image', 'background', 'remove', 'transparent'],
    icon: 'Layers',
    featured: true,
    relatedTools: ['image-cropper', 'png-to-jpg-converter', 'photo-editor'],
    componentName: 'BackgroundRemoverTool',
    metaTitle: 'Background Remover - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online background remover. Remove background from images automatically.',
    metaKeywords: ['background remover', 'remove background', 'transparent background'],
    howToUse: [
      'Upload your image',
      'Click "Remove Background"',
      'Wait for processing',
      'Download image with transparent background',
    ],
    inputType: 'file',
    outputType: 'file',
    maxFileSize: 10,
    acceptedFormats: ['image/*'],
  },
  {
    id: 28,
    slug: 'image-color-picker',
    name: 'Image Color Picker',
    shortDescription: 'Pick colors from images',
    fullDescription: 'Free online image color picker. Extract color codes from any image.',
    category: ToolCategory.IMAGE,
    tags: ['image', 'color', 'picker', 'eyedropper'],
    icon: 'Pipette',
    featured: false,
    relatedTools: ['color-picker-tool', 'gradient-generator'],
    componentName: 'ImageColorPickerTool',
    metaTitle: 'Image Color Picker - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online image color picker. Extract color codes from any image.',
    metaKeywords: ['image color picker', 'pick color from image', 'eyedropper tool'],
    howToUse: [
      'Upload your image',
      'Click on any pixel',
      'View color codes (HEX, RGB, HSL)',
      'Copy color codes',
    ],
    inputType: 'file',
    outputType: 'text',
    maxFileSize: 10,
    acceptedFormats: ['image/*'],
  },
  {
    id: 29,
    slug: 'image-grayscale-converter',
    name: 'Image Grayscale Converter',
    shortDescription: 'Convert images to grayscale/black and white',
    fullDescription: 'Free online grayscale converter. Convert color images to black and white.',
    category: ToolCategory.IMAGE,
    tags: ['image', 'grayscale', 'black-white', 'filter'],
    icon: 'Palette',
    featured: false,
    relatedTools: ['image-filter-effects', 'photo-editor'],
    componentName: 'ImageGrayscaleTool',
    metaTitle: 'Image Grayscale Converter - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online grayscale converter. Convert color images to black and white.',
    metaKeywords: ['grayscale converter', 'black and white image', 'convert to grayscale'],
    howToUse: [
      'Upload your color image',
      'Click "Convert to Grayscale"',
      'Wait for processing',
      'Download grayscale image',
    ],
    inputType: 'file',
    outputType: 'file',
    maxFileSize: 10,
    acceptedFormats: ['image/*'],
  },
  {
    id: 30,
    slug: 'photo-editor',
    name: 'Photo Editor',
    shortDescription: 'Edit photos with filters and adjustments',
    fullDescription: 'Free online photo editor. Edit photos with filters, adjustments, and effects.',
    category: ToolCategory.IMAGE,
    tags: ['photo', 'editor', 'edit', 'image'],
    icon: 'ImageEdit',
    featured: true,
    relatedTools: ['image-filter-effects', 'image-cropper', 'background-remover'],
    componentName: 'PhotoEditorTool',
    metaTitle: 'Photo Editor - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online photo editor. Edit photos with filters, adjustments, and effects.',
    metaKeywords: ['photo editor', 'image editor', 'edit photos online'],
    howToUse: [
      'Upload your photo',
      'Apply filters and adjustments',
      'Use editing tools',
      'Download edited photo',
    ],
    inputType: 'file',
    outputType: 'file',
    maxFileSize: 10,
    acceptedFormats: ['image/*'],
  },
  {
    id: 31,
    slug: 'meme-generator',
    name: 'Meme Generator',
    shortDescription: 'Create memes with text overlays',
    fullDescription: 'Free online meme generator. Create custom memes with text overlays.',
    category: ToolCategory.IMAGE,
    tags: ['meme', 'generator', 'text', 'funny'],
    icon: 'Laugh',
    featured: false,
    relatedTools: ['photo-editor', 'image-filter-effects'],
    componentName: 'MemeGeneratorTool',
    metaTitle: 'Meme Generator - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online meme generator. Create custom memes with text overlays.',
    metaKeywords: ['meme generator', 'create meme', 'meme maker'],
    howToUse: [
      'Upload image or choose template',
      'Add top and bottom text',
      'Customize font and style',
      'Download your meme',
    ],
    inputType: 'file',
    outputType: 'file',
    maxFileSize: 10,
    acceptedFormats: ['image/*'],
  },
  {
    id: 32,
    slug: 'qr-code-generator',
    name: 'QR Code Generator',
    shortDescription: 'Generate QR codes for URLs and text',
    fullDescription: 'Free online QR code generator. Create QR codes for URLs, text, and more.',
    category: ToolCategory.IMAGE,
    tags: ['qr', 'qrcode', 'generator', 'barcode'],
    icon: 'QrCode',
    featured: true,
    relatedTools: ['barcode-generator', 'url-encoder'],
    componentName: 'QrCodeGeneratorTool',
    metaTitle: 'QR Code Generator - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online QR code generator. Create QR codes for URLs and text instantly.',
    metaKeywords: ['qr code generator', 'generate qr code', 'create qr code'],
    howToUse: [
      'Enter URL or text',
      'Customize QR code size and color',
      'Click "Generate QR Code"',
      'Download QR code image',
    ],
    inputType: 'text',
    outputType: 'file',
  },
  {
    id: 33,
    slug: 'barcode-generator',
    name: 'Barcode Generator',
    shortDescription: 'Generate barcodes for products',
    fullDescription: 'Free online barcode generator. Create barcodes in multiple formats.',
    category: ToolCategory.IMAGE,
    tags: ['barcode', 'generator', 'upc', 'ean'],
    icon: 'Barcode',
    featured: false,
    relatedTools: ['qr-code-generator', 'uuid-generator'],
    componentName: 'BarcodeGeneratorTool',
    metaTitle: 'Barcode Generator - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online barcode generator. Create barcodes in multiple formats instantly.',
    metaKeywords: ['barcode generator', 'generate barcode', 'create barcode'],
    howToUse: [
      'Enter barcode value',
      'Select barcode format',
      'Click "Generate Barcode"',
      'Download barcode image',
    ],
    inputType: 'text',
    outputType: 'file',
  },

  // TEXT TOOLS (20) - Continue from here
  {
    id: 34,
    slug: 'word-counter',
    name: 'Word Counter',
    shortDescription: 'Count words, characters, and paragraphs',
    fullDescription: 'Free online word counter. Count words, characters, sentences, and paragraphs in your text.',
    category: ToolCategory.TEXT,
    tags: ['word', 'counter', 'count', 'text', 'characters'],
    icon: 'FileText',
    featured: true,
    relatedTools: ['character-counter', 'text-sorter', 'duplicate-line-remover'],
    componentName: 'WordCounterTool',
    metaTitle: 'Word Counter - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online word counter. Count words, characters, sentences instantly.',
    metaKeywords: ['word counter', 'character counter', 'count words', 'text counter'],
    howToUse: [
      'Paste or type your text',
      'View word count instantly',
      'See character and sentence counts',
      'Use for essays, articles, and documents',
    ],
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 35,
    slug: 'character-counter',
    name: 'Character Counter',
    shortDescription: 'Count characters and letters',
    fullDescription: 'Free online character counter. Count characters, letters, and spaces in your text.',
    category: ToolCategory.TEXT,
    tags: ['character', 'counter', 'count', 'text'],
    icon: 'Type',
    featured: false,
    relatedTools: ['word-counter', 'text-sorter'],
    componentName: 'CharacterCounterTool',
    metaTitle: 'Character Counter - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online character counter. Count characters and letters instantly.',
    metaKeywords: ['character counter', 'count characters', 'letter counter'],
    howToUse: [
      'Paste or type your text',
      'View character count instantly',
      'See with and without spaces',
      'Perfect for social media posts',
    ],
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 36,
    slug: 'case-converter',
    name: 'Case Converter',
    shortDescription: 'Convert text case (uppercase, lowercase, title)',
    fullDescription: 'Free online case converter. Convert text to uppercase, lowercase, title case, and sentence case.',
    category: ToolCategory.TEXT,
    tags: ['case', 'converter', 'uppercase', 'lowercase', 'text'],
    icon: 'CaseSensitive',
    featured: true,
    relatedTools: ['text-reverser', 'text-replacer', 'word-counter'],
    componentName: 'CaseConverterTool',
    metaTitle: 'Case Converter - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online case converter. Convert text to uppercase, lowercase, title case instantly.',
    metaKeywords: ['case converter', 'uppercase', 'lowercase', 'title case', 'convert case'],
    howToUse: [
      'Paste your text',
      'Choose conversion type',
      'Click convert button',
      'Copy converted text',
    ],
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 37,
    slug: 'text-to-speech',
    name: 'Text to Speech',
    shortDescription: 'Convert text to spoken audio',
    fullDescription: 'Free online text to speech converter. Convert written text to spoken audio using natural voices.',
    category: ToolCategory.TEXT,
    tags: ['text', 'speech', 'audio', 'tts', 'voice'],
    icon: 'Volume2',
    featured: true,
    relatedTools: ['speech-to-text', 'text-to-mp3'],
    componentName: 'TextToSpeechTool',
    metaTitle: 'Text to Speech - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online text to speech converter. Convert text to natural spoken audio.',
    metaKeywords: ['text to speech', 'tts', 'text to audio', 'speech synthesis'],
    howToUse: [
      'Enter your text',
      'Select voice and language',
      'Click "Play" or "Generate"',
      'Listen or download audio',
    ],
    inputType: 'text',
    outputType: 'file',
  },
  {
    id: 38,
    slug: 'speech-to-text',
    name: 'Speech to Text',
    shortDescription: 'Convert speech to written text',
    fullDescription: 'Free online speech to text converter. Convert spoken audio to written text using speech recognition.',
    category: ToolCategory.TEXT,
    tags: ['speech', 'text', 'transcribe', 'voice', 'recognition'],
    icon: 'Mic',
    featured: false,
    relatedTools: ['text-to-speech', 'audio-trimmer'],
    componentName: 'SpeechToTextTool',
    metaTitle: 'Speech to Text - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online speech to text converter. Transcribe audio to text instantly.',
    metaKeywords: ['speech to text', 'transcribe audio', 'voice to text', 'speech recognition'],
    howToUse: [
      'Click microphone button',
      'Speak into your microphone',
      'Watch text appear in real-time',
      'Edit and copy transcribed text',
    ],
    inputType: 'file',
    outputType: 'text',
  },
  {
    id: 39,
    slug: 'lorem-ipsum-generator',
    name: 'Lorem Ipsum Generator',
    shortDescription: 'Generate placeholder Lorem Ipsum text',
    fullDescription: 'Free Lorem Ipsum generator. Generate placeholder text for designs and mockups.',
    category: ToolCategory.TEXT,
    tags: ['lorem', 'ipsum', 'placeholder', 'text', 'generator'],
    icon: 'FileType',
    featured: false,
    relatedTools: ['word-counter', 'text-replacer', 'random-number-generator'],
    componentName: 'LoremIpsumTool',
    metaTitle: 'Lorem Ipsum Generator - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free Lorem Ipsum generator. Generate placeholder text instantly.',
    metaKeywords: ['lorem ipsum', 'placeholder text', 'dummy text', 'filler text'],
    howToUse: [
      'Choose number of paragraphs',
      'Select words, sentences, or paragraphs',
      'Click "Generate"',
      'Copy placeholder text',
    ],
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 40,
    slug: 'text-diff-checker',
    name: 'Text Diff Checker',
    shortDescription: 'Compare two texts and find differences',
    fullDescription: 'Free online text diff checker. Compare two texts and highlight differences between them.',
    category: ToolCategory.TEXT,
    tags: ['text', 'diff', 'compare', 'difference', 'merge'],
    icon: 'GitCompare',
    featured: true,
    relatedTools: ['text-replacer', 'duplicate-line-remover'],
    componentName: 'TextDiffTool',
    metaTitle: 'Text Diff Checker - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online text diff checker. Compare texts and find differences instantly.',
    metaKeywords: ['text diff', 'compare text', 'text difference', 'diff tool'],
    howToUse: [
      'Paste first text in left panel',
      'Paste second text in right panel',
      'View highlighted differences',
      'See additions and deletions',
    ],
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 41,
    slug: 'duplicate-line-remover',
    name: 'Duplicate Line Remover',
    shortDescription: 'Remove duplicate lines from text',
    fullDescription: 'Free online duplicate line remover. Remove duplicate lines and keep unique entries.',
    category: ToolCategory.TEXT,
    tags: ['duplicate', 'remove', 'unique', 'text', 'lines'],
    icon: 'FileMinus',
    featured: false,
    relatedTools: ['text-sorter', 'text-diff-checker', 'line-break-remover'],
    componentName: 'DuplicateLineRemoverTool',
    metaTitle: 'Duplicate Line Remover - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online duplicate line remover. Remove duplicate lines instantly.',
    metaKeywords: ['remove duplicates', 'duplicate line remover', 'unique lines'],
    howToUse: [
      'Paste text with duplicates',
      'Click "Remove Duplicates"',
      'View unique lines only',
      'Copy clean text',
    ],
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 42,
    slug: 'text-reverser',
    name: 'Text Reverser',
    shortDescription: 'Reverse text and strings',
    fullDescription: 'Free online text reverser. Reverse text, words, or letters instantly.',
    category: ToolCategory.TEXT,
    tags: ['reverse', 'text', 'flip', 'backward'],
    icon: 'ArrowLeftRight',
    featured: false,
    relatedTools: ['case-converter', 'text-replacer', 'morse-code-translator'],
    componentName: 'TextReverserTool',
    metaTitle: 'Text Reverser - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online text reverser. Reverse text and strings instantly.',
    metaKeywords: ['text reverser', 'reverse text', 'flip text', 'backward text'],
    howToUse: [
      'Enter your text',
      'Choose reverse type (characters, words, lines)',
      'Click "Reverse"',
      'Copy reversed text',
    ],
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 43,
    slug: 'text-sorter',
    name: 'Text Sorter',
    shortDescription: 'Sort text lines alphabetically',
    fullDescription: 'Free online text sorter. Sort text lines alphabetically in ascending or descending order.',
    category: ToolCategory.TEXT,
    tags: ['sort', 'text', 'alphabetical', 'order'],
    icon: 'ArrowUpDown',
    featured: false,
    relatedTools: ['duplicate-line-remover', 'word-counter', 'line-break-remover'],
    componentName: 'TextSorterTool',
    metaTitle: 'Text Sorter - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online text sorter. Sort text lines alphabetically instantly.',
    metaKeywords: ['text sorter', 'sort text', 'alphabetical order', 'sort lines'],
    howToUse: [
      'Paste your text',
      'Choose sort order (A-Z or Z-A)',
      'Click "Sort"',
      'Copy sorted text',
    ],
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 44,
    slug: 'line-break-remover',
    name: 'Line Break Remover',
    shortDescription: 'Remove line breaks from text',
    fullDescription: 'Free online line break remover. Remove line breaks and join text into single line.',
    category: ToolCategory.TEXT,
    tags: ['line', 'break', 'remove', 'text'],
    icon: 'WrapText',
    featured: false,
    relatedTools: ['whitespace-remover', 'text-sorter', 'duplicate-line-remover'],
    componentName: 'LineBreakRemoverTool',
    metaTitle: 'Line Break Remover - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online line break remover. Remove line breaks from text instantly.',
    metaKeywords: ['line break remover', 'remove line breaks', 'join lines'],
    howToUse: [
      'Paste text with line breaks',
      'Click "Remove Line Breaks"',
      'View text on single line',
      'Copy result',
    ],
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 45,
    slug: 'whitespace-remover',
    name: 'Whitespace Remover',
    shortDescription: 'Remove extra whitespace from text',
    fullDescription: 'Free online whitespace remover. Remove extra spaces, tabs, and whitespace from text.',
    category: ToolCategory.TEXT,
    tags: ['whitespace', 'space', 'remove', 'text', 'trim'],
    icon: 'Space',
    featured: false,
    relatedTools: ['line-break-remover', 'text-sorter', 'html-minifier'],
    componentName: 'WhitespaceRemoverTool',
    metaTitle: 'Whitespace Remover - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online whitespace remover. Remove extra spaces and whitespace instantly.',
    metaKeywords: ['whitespace remover', 'remove spaces', 'trim text', 'remove extra spaces'],
    howToUse: [
      'Paste text with extra whitespace',
      'Click "Remove Whitespace"',
      'View cleaned text',
      'Copy result',
    ],
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 46,
    slug: 'text-replacer',
    name: 'Text Replacer (Find & Replace)',
    shortDescription: 'Find and replace text in bulk',
    fullDescription: 'Free online text replacer. Find and replace text, words, or patterns in bulk.',
    category: ToolCategory.TEXT,
    tags: ['find', 'replace', 'text', 'search', 'substitute'],
    icon: 'Replace',
    featured: false,
    relatedTools: ['text-diff-checker', 'regex-tester', 'case-converter'],
    componentName: 'TextReplacerTool',
    metaTitle: 'Text Replacer - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online text replacer. Find and replace text in bulk instantly.',
    metaKeywords: ['text replacer', 'find and replace', 'replace text', 'bulk replace'],
    howToUse: [
      'Paste your text',
      'Enter text to find',
      'Enter replacement text',
      'Click "Replace All"',
    ],
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 47,
    slug: 'csv-to-json-converter',
    name: 'CSV to JSON Converter',
    shortDescription: 'Convert CSV data to JSON format',
    fullDescription: 'Free online CSV to JSON converter. Convert CSV data to JSON format instantly.',
    category: ToolCategory.TEXT,
    tags: ['csv', 'json', 'converter', 'data'],
    icon: 'Table',
    featured: true,
    relatedTools: ['json-to-csv-converter', 'json-formatter', 'xml-to-json-converter'],
    componentName: 'CsvToJsonTool',
    metaTitle: 'CSV to JSON Converter - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online CSV to JSON converter. Convert CSV to JSON format instantly.',
    metaKeywords: ['csv to json', 'convert csv to json', 'csv converter'],
    howToUse: [
      'Paste CSV data',
      'Click "Convert to JSON"',
      'View formatted JSON',
      'Copy or download JSON',
    ],
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 48,
    slug: 'json-to-csv-converter',
    name: 'JSON to CSV Converter',
    shortDescription: 'Convert JSON data to CSV format',
    fullDescription: 'Free online JSON to CSV converter. Convert JSON data to CSV format instantly.',
    category: ToolCategory.TEXT,
    tags: ['json', 'csv', 'converter', 'data'],
    icon: 'Table',
    featured: false,
    relatedTools: ['csv-to-json-converter', 'json-formatter', 'json-minifier'],
    componentName: 'JsonToCsvTool',
    metaTitle: 'JSON to CSV Converter - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online JSON to CSV converter. Convert JSON to CSV format instantly.',
    metaKeywords: ['json to csv', 'convert json to csv', 'json converter'],
    howToUse: [
      'Paste JSON data',
      'Click "Convert to CSV"',
      'View CSV output',
      'Copy or download CSV',
    ],
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 49,
    slug: 'xml-to-json-converter',
    name: 'XML to JSON Converter',
    shortDescription: 'Convert XML data to JSON format',
    fullDescription: 'Free online XML to JSON converter. Convert XML data to JSON format instantly.',
    category: ToolCategory.TEXT,
    tags: ['xml', 'json', 'converter', 'data'],
    icon: 'Code',
    featured: false,
    relatedTools: ['csv-to-json-converter', 'xml-formatter', 'json-formatter'],
    componentName: 'XmlToJsonTool',
    metaTitle: 'XML to JSON Converter - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online XML to JSON converter. Convert XML to JSON format instantly.',
    metaKeywords: ['xml to json', 'convert xml to json', 'xml converter'],
    howToUse: [
      'Paste XML data',
      'Click "Convert to JSON"',
      'View JSON output',
      'Copy or download JSON',
    ],
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 50,
    slug: 'markdown-to-html',
    name: 'Markdown to HTML',
    shortDescription: 'Convert Markdown to HTML',
    fullDescription: 'Free online Markdown to HTML converter. Convert Markdown text to HTML markup.',
    category: ToolCategory.TEXT,
    tags: ['markdown', 'html', 'converter', 'markup'],
    icon: 'FileCode',
    featured: false,
    relatedTools: ['html-to-markdown', 'html-formatter', 'html-minifier'],
    componentName: 'MarkdownToHtmlTool',
    metaTitle: 'Markdown to HTML - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online Markdown to HTML converter. Convert Markdown to HTML instantly.',
    metaKeywords: ['markdown to html', 'convert markdown', 'md to html'],
    howToUse: [
      'Paste Markdown text',
      'Click "Convert to HTML"',
      'View HTML output',
      'Copy or download HTML',
    ],
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 51,
    slug: 'html-to-markdown',
    name: 'HTML to Markdown',
    shortDescription: 'Convert HTML to Markdown',
    fullDescription: 'Free online HTML to Markdown converter. Convert HTML markup to Markdown text.',
    category: ToolCategory.TEXT,
    tags: ['html', 'markdown', 'converter', 'markup'],
    icon: 'FileCode',
    featured: false,
    relatedTools: ['markdown-to-html', 'html-formatter', 'html-entity-encoder'],
    componentName: 'HtmlToMarkdownTool',
    metaTitle: 'HTML to Markdown - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online HTML to Markdown converter. Convert HTML to Markdown instantly.',
    metaKeywords: ['html to markdown', 'convert html', 'html to md'],
    howToUse: [
      'Paste HTML code',
      'Click "Convert to Markdown"',
      'View Markdown output',
      'Copy or download Markdown',
    ],
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 52,
    slug: 'text-encryptor-decryptor',
    name: 'Text Encryptor/Decryptor',
    shortDescription: 'Encrypt and decrypt text securely',
    fullDescription: 'Free online text encryptor and decryptor. Encrypt and decrypt text using strong encryption.',
    category: ToolCategory.TEXT,
    tags: ['encrypt', 'decrypt', 'text', 'security', 'cipher'],
    icon: 'Lock',
    featured: false,
    relatedTools: ['aes-encryptor', 'password-generator', 'base64-encoder'],
    componentName: 'TextEncryptorTool',
    metaTitle: 'Text Encryptor/Decryptor - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online text encryptor and decryptor. Encrypt and decrypt text securely.',
    metaKeywords: ['text encryptor', 'encrypt text', 'decrypt text', 'text cipher'],
    howToUse: [
      'Enter text to encrypt/decrypt',
      'Enter encryption password',
      'Choose encrypt or decrypt',
      'Copy result',
    ],
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 53,
    slug: 'morse-code-translator',
    name: 'Morse Code Translator',
    shortDescription: 'Translate text to/from Morse code',
    fullDescription: 'Free online Morse code translator. Convert text to Morse code and decode Morse code to text.',
    category: ToolCategory.TEXT,
    tags: ['morse', 'code', 'translator', 'encode', 'decode'],
    icon: 'Radio',
    featured: false,
    relatedTools: ['text-encryptor', 'base64-encoder', 'text-reverser'],
    componentName: 'MorseCodeTool',
    metaTitle: 'Morse Code Translator - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online Morse code translator. Convert text to Morse code instantly.',
    metaKeywords: ['morse code', 'morse translator', 'morse code converter', 'text to morse'],
    howToUse: [
      'Enter text or Morse code',
      'Choose translation direction',
      'Click "Translate"',
      'Copy result',
    ],
    inputType: 'text',
    outputType: 'text',
  },

  // CODE TOOLS (18)
  {
    id: 54,
    slug: 'json-formatter',
    name: 'JSON Formatter & Validator',
    shortDescription: 'Format and validate JSON data',
    fullDescription: 'Free online JSON formatter and validator. Format, beautify and validate JSON data instantly. No login required. Fast, secure, and 100% free forever.',
    category: ToolCategory.CODE,
    tags: ['json', 'formatter', 'validator', 'beautifier', 'parse', 'minify'],
    icon: 'Braces',
    featured: true,
    relatedTools: ['json-minifier', 'xml-formatter', 'csv-to-json', 'json-to-csv'],
    componentName: 'JsonFormatterTool',
    metaTitle: 'JSON Formatter & Validator - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online JSON formatter and validator. Format, beautify and validate JSON instantly. No login required. Fast, secure, and 100% free forever.',
    metaKeywords: ['json formatter', 'json validator', 'beautify json', 'json parser', 'format json online'],
    howToUse: [
      'Paste your JSON data in the input area',
      'Click "Format JSON" to beautify',
      'Use "Validate" to check for syntax errors',
      'Click "Copy" or "Download" to save results',
    ],
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 55,
    slug: 'xml-formatter',
    name: 'XML Formatter & Validator',
    shortDescription: 'Format and validate XML data',
    fullDescription: 'Free online XML formatter and validator. Format, beautify and validate XML data instantly.',
    category: ToolCategory.CODE,
    tags: ['xml', 'formatter', 'validator', 'beautifier'],
    icon: 'Code',
    featured: false,
    relatedTools: ['json-formatter', 'html-formatter', 'xml-to-json-converter'],
    componentName: 'XmlFormatterTool',
    metaTitle: 'XML Formatter & Validator - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online XML formatter and validator. Format and beautify XML instantly.',
    metaKeywords: ['xml formatter', 'xml validator', 'beautify xml', 'format xml'],
    howToUse: [
      'Paste XML code',
      'Click "Format XML"',
      'View formatted XML',
      'Copy or download result',
    ],
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 56,
    slug: 'html-formatter',
    name: 'HTML Formatter & Beautifier',
    shortDescription: 'Format and beautify HTML code',
    fullDescription: 'Free online HTML formatter and beautifier. Format and beautify HTML code instantly.',
    category: ToolCategory.CODE,
    tags: ['html', 'formatter', 'beautifier', 'code'],
    icon: 'Code2',
    featured: true,
    relatedTools: ['css-formatter', 'js-formatter', 'html-minifier'],
    componentName: 'HtmlFormatterTool',
    metaTitle: 'HTML Formatter & Beautifier - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online HTML formatter and beautifier. Format HTML code instantly.',
    metaKeywords: ['html formatter', 'beautify html', 'format html', 'html beautifier'],
    howToUse: [
      'Paste HTML code',
      'Click "Format HTML"',
      'View beautified HTML',
      'Copy or download result',
    ],
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 57,
    slug: 'css-formatter',
    name: 'CSS Formatter & Beautifier',
    shortDescription: 'Format and beautify CSS code',
    fullDescription: 'Free online CSS formatter and beautifier. Format and beautify CSS stylesheets instantly.',
    category: ToolCategory.CODE,
    tags: ['css', 'formatter', 'beautifier', 'stylesheet'],
    icon: 'Palette',
    featured: false,
    relatedTools: ['html-formatter', 'css-minifier', 'js-formatter'],
    componentName: 'CssFormatterTool',
    metaTitle: 'CSS Formatter & Beautifier - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online CSS formatter and beautifier. Format CSS code instantly.',
    metaKeywords: ['css formatter', 'beautify css', 'format css', 'css beautifier'],
    howToUse: [
      'Paste CSS code',
      'Click "Format CSS"',
      'View beautified CSS',
      'Copy or download result',
    ],
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 58,
    slug: 'javascript-formatter',
    name: 'JavaScript Formatter & Beautifier',
    shortDescription: 'Format and beautify JavaScript code',
    fullDescription: 'Free online JavaScript formatter and beautifier. Format and beautify JS code instantly.',
    category: ToolCategory.CODE,
    tags: ['javascript', 'js', 'formatter', 'beautifier', 'code'],
    icon: 'FileCode',
    featured: true,
    relatedTools: ['html-formatter', 'css-formatter', 'js-minifier'],
    componentName: 'JsFormatterTool',
    metaTitle: 'JavaScript Formatter - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online JavaScript formatter and beautifier. Format JS code instantly.',
    metaKeywords: ['javascript formatter', 'js formatter', 'beautify javascript', 'format js'],
    howToUse: [
      'Paste JavaScript code',
      'Click "Format JS"',
      'View beautified JavaScript',
      'Copy or download result',
    ],
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 59,
    slug: 'sql-formatter',
    name: 'SQL Formatter',
    shortDescription: 'Format and beautify SQL queries',
    fullDescription: 'Free online SQL formatter. Format and beautify SQL queries and statements.',
    category: ToolCategory.CODE,
    tags: ['sql', 'formatter', 'query', 'database'],
    icon: 'Database',
    featured: false,
    relatedTools: ['json-formatter', 'xml-formatter'],
    componentName: 'SqlFormatterTool',
    metaTitle: 'SQL Formatter - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online SQL formatter. Format and beautify SQL queries instantly.',
    metaKeywords: ['sql formatter', 'format sql', 'beautify sql', 'sql query formatter'],
    howToUse: [
      'Paste SQL query',
      'Click "Format SQL"',
      'View formatted SQL',
      'Copy result',
    ],
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 60,
    slug: 'json-minifier',
    name: 'JSON Minifier',
    shortDescription: 'Minify JSON data',
    fullDescription: 'Free online JSON minifier. Compress JSON data by removing whitespace.',
    category: ToolCategory.CODE,
    tags: ['json', 'minifier', 'compress', 'minify'],
    icon: 'Minimize2',
    featured: false,
    relatedTools: ['json-formatter', 'css-minifier', 'js-minifier'],
    componentName: 'JsonMinifierTool',
    metaTitle: 'JSON Minifier - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online JSON minifier. Compress JSON by removing whitespace instantly.',
    metaKeywords: ['json minifier', 'minify json', 'compress json', 'json compressor'],
    howToUse: [
      'Paste formatted JSON',
      'Click "Minify JSON"',
      'View compressed JSON',
      'Copy or download result',
    ],
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 61,
    slug: 'css-minifier',
    name: 'CSS Minifier',
    shortDescription: 'Minify CSS code',
    fullDescription: 'Free online CSS minifier. Compress CSS code by removing whitespace and comments.',
    category: ToolCategory.CODE,
    tags: ['css', 'minifier', 'compress', 'minify'],
    icon: 'Minimize2',
    featured: false,
    relatedTools: ['css-formatter', 'js-minifier', 'html-minifier'],
    componentName: 'CssMinifierTool',
    metaTitle: 'CSS Minifier - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online CSS minifier. Compress CSS code instantly.',
    metaKeywords: ['css minifier', 'minify css', 'compress css', 'css compressor'],
    howToUse: [
      'Paste CSS code',
      'Click "Minify CSS"',
      'View compressed CSS',
      'Copy or download result',
    ],
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 62,
    slug: 'javascript-minifier',
    name: 'JavaScript Minifier',
    shortDescription: 'Minify JavaScript code',
    fullDescription: 'Free online JavaScript minifier. Compress JS code by removing whitespace and comments.',
    category: ToolCategory.CODE,
    tags: ['javascript', 'js', 'minifier', 'compress', 'minify'],
    icon: 'Minimize2',
    featured: false,
    relatedTools: ['js-formatter', 'css-minifier', 'html-minifier'],
    componentName: 'JsMinifierTool',
    metaTitle: 'JavaScript Minifier - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online JavaScript minifier. Compress JS code instantly.',
    metaKeywords: ['javascript minifier', 'js minifier', 'minify javascript', 'compress js'],
    howToUse: [
      'Paste JavaScript code',
      'Click "Minify JS"',
      'View compressed JavaScript',
      'Copy or download result',
    ],
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 63,
    slug: 'html-minifier',
    name: 'HTML Minifier',
    shortDescription: 'Minify HTML code',
    fullDescription: 'Free online HTML minifier. Compress HTML code by removing whitespace and comments.',
    category: ToolCategory.CODE,
    tags: ['html', 'minifier', 'compress', 'minify'],
    icon: 'Minimize2',
    featured: false,
    relatedTools: ['html-formatter', 'css-minifier', 'js-minifier'],
    componentName: 'HtmlMinifierTool',
    metaTitle: 'HTML Minifier - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online HTML minifier. Compress HTML code instantly.',
    metaKeywords: ['html minifier', 'minify html', 'compress html', 'html compressor'],
    howToUse: [
      'Paste HTML code',
      'Click "Minify HTML"',
      'View compressed HTML',
      'Copy or download result',
    ],
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 64,
    slug: 'syntax-highlighter',
    name: 'Code Syntax Highlighter',
    shortDescription: 'Highlight code syntax for multiple languages',
    fullDescription: 'Free online code syntax highlighter. Add syntax highlighting to code in multiple languages.',
    category: ToolCategory.CODE,
    tags: ['syntax', 'highlighter', 'code', 'color'],
    icon: 'Code',
    featured: false,
    relatedTools: ['json-formatter', 'html-formatter', 'js-formatter'],
    componentName: 'SyntaxHighlighterTool',
    metaTitle: 'Code Syntax Highlighter - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online code syntax highlighter. Add syntax highlighting to code.',
    metaKeywords: ['syntax highlighter', 'code highlighter', 'highlight code'],
    howToUse: [
      'Paste your code',
      'Select programming language',
      'View highlighted code',
      'Copy HTML output',
    ],
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 65,
    slug: 'regex-tester',
    name: 'RegEx Tester',
    shortDescription: 'Test and validate regular expressions',
    fullDescription: 'Free online RegEx tester. Test and validate regular expressions with real-time matching.',
    category: ToolCategory.CODE,
    tags: ['regex', 'regexp', 'tester', 'pattern', 'match'],
    icon: 'Search',
    featured: true,
    relatedTools: ['text-replacer', 'text-diff-checker'],
    componentName: 'RegexTesterTool',
    metaTitle: 'RegEx Tester - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online RegEx tester. Test regular expressions with real-time matching.',
    metaKeywords: ['regex tester', 'regexp tester', 'regular expression', 'pattern tester'],
    howToUse: [
      'Enter your regular expression',
      'Enter test string',
      'View matches instantly',
      'Test different patterns',
    ],
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 66,
    slug: 'color-picker-tool',
    name: 'Color Picker Tool',
    shortDescription: 'Pick and convert color codes',
    fullDescription: 'Free online color picker. Pick colors and convert between HEX, RGB, HSL formats.',
    category: ToolCategory.CODE,
    tags: ['color', 'picker', 'hex', 'rgb', 'hsl'],
    icon: 'Palette',
    featured: true,
    relatedTools: ['gradient-generator', 'image-color-picker', 'css-formatter'],
    componentName: 'ColorPickerTool',
    metaTitle: 'Color Picker Tool - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online color picker. Pick colors and convert between formats.',
    metaKeywords: ['color picker', 'hex color', 'rgb color', 'color converter'],
    howToUse: [
      'Click on color picker',
      'Select your color',
      'View color codes (HEX, RGB, HSL)',
      'Copy color code',
    ],
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 67,
    slug: 'gradient-generator',
    name: 'Gradient Generator',
    shortDescription: 'Generate CSS gradients',
    fullDescription: 'Free online gradient generator. Create beautiful CSS gradients with live preview.',
    category: ToolCategory.CODE,
    tags: ['gradient', 'css', 'generator', 'color'],
    icon: 'Palette',
    featured: false,
    relatedTools: ['color-picker-tool', 'box-shadow-generator', 'css-formatter'],
    componentName: 'GradientGeneratorTool',
    metaTitle: 'Gradient Generator - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online gradient generator. Create beautiful CSS gradients.',
    metaKeywords: ['gradient generator', 'css gradient', 'linear gradient', 'radial gradient'],
    howToUse: [
      'Choose gradient colors',
      'Select gradient type',
      'Adjust angle and position',
      'Copy CSS code',
    ],
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 68,
    slug: 'box-shadow-generator',
    name: 'Box Shadow Generator',
    shortDescription: 'Generate CSS box shadows',
    fullDescription: 'Free online box shadow generator. Create CSS box shadows with live preview.',
    category: ToolCategory.CODE,
    tags: ['box-shadow', 'css', 'generator', 'shadow'],
    icon: 'Square',
    featured: false,
    relatedTools: ['gradient-generator', 'border-radius-generator', 'css-formatter'],
    componentName: 'BoxShadowGeneratorTool',
    metaTitle: 'Box Shadow Generator - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online box shadow generator. Create CSS box shadows with preview.',
    metaKeywords: ['box shadow generator', 'css box shadow', 'shadow generator'],
    howToUse: [
      'Adjust shadow properties',
      'View live preview',
      'Customize colors',
      'Copy CSS code',
    ],
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 69,
    slug: 'border-radius-generator',
    name: 'Border Radius Generator',
    shortDescription: 'Generate CSS border radius',
    fullDescription: 'Free online border radius generator. Create CSS border radius with live preview.',
    category: ToolCategory.CODE,
    tags: ['border-radius', 'css', 'generator', 'rounded'],
    icon: 'Circle',
    featured: false,
    relatedTools: ['box-shadow-generator', 'gradient-generator', 'css-formatter'],
    componentName: 'BorderRadiusGeneratorTool',
    metaTitle: 'Border Radius Generator - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online border radius generator. Create CSS border radius with preview.',
    metaKeywords: ['border radius generator', 'css border radius', 'rounded corners'],
    howToUse: [
      'Adjust corner radius values',
      'View live preview',
      'Use individual corners',
      'Copy CSS code',
    ],
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 70,
    slug: 'html-entity-encoder',
    name: 'HTML Entity Encoder/Decoder',
    shortDescription: 'Encode and decode HTML entities',
    fullDescription: 'Free online HTML entity encoder and decoder. Convert characters to HTML entities and back.',
    category: ToolCategory.CODE,
    tags: ['html', 'entity', 'encode', 'decode', 'escape'],
    icon: 'Code',
    featured: false,
    relatedTools: ['url-encoder', 'base64-encoder', 'html-formatter'],
    componentName: 'HtmlEntityEncoderTool',
    metaTitle: 'HTML Entity Encoder - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online HTML entity encoder and decoder. Convert HTML entities instantly.',
    metaKeywords: ['html entity encoder', 'html escape', 'encode html', 'decode html entities'],
    howToUse: [
      'Enter text or HTML entities',
      'Choose encode or decode',
      'Click process button',
      'Copy result',
    ],
    inputType: 'text',
    outputType: 'text',
  },
  {
    id: 71,
    slug: 'url-encoder-decoder',
    name: 'URL Encoder/Decoder',
    shortDescription: 'Encode and decode URLs',
    fullDescription: 'Free online URL encoder and decoder. Encode and decode URL parameters and strings.',
    category: ToolCategory.CODE,
    tags: ['url', 'encode', 'decode', 'uri', 'percent'],
    icon: 'Link',
    featured: false,
    relatedTools: ['html-entity-encoder', 'base64-encoder', 'qr-code-generator'],
    componentName: 'UrlEncoderTool',
    metaTitle: 'URL Encoder/Decoder - Free Online Tool | ToolGalaxyHub',
    metaDescription: 'Free online URL encoder and decoder. Encode and decode URLs instantly.',
    metaKeywords: ['url encoder', 'url decoder', 'encode url', 'decode url', 'percent encoding'],
    howToUse: [
      'Enter URL or encoded string',
      'Choose encode or decode',
      'Click process button',
      'Copy result',
    ],
    inputType: 'text',
    outputType: 'text',
  },

  // Continue with remaining categories in next message due to length...
  // SEO TOOLS (12), VIDEO TOOLS (8), AUDIO TOOLS (10), SECURITY TOOLS (14)
]

// Helper functions
export function getToolBySlug(slug: string): Tool | undefined {
  return allTools.find(tool => tool.slug === slug)
}

export function getToolsByCategory(category: ToolCategory): Tool[] {
  return allTools.filter(tool => tool.category === category)
}

export function searchTools(query: string): Tool[] {
  const lowerQuery = query.toLowerCase()
  return allTools.filter(tool =>
    tool.name.toLowerCase().includes(lowerQuery) ||
    tool.shortDescription.toLowerCase().includes(lowerQuery) ||
    tool.tags.some(tag => tag.toLowerCase().includes(lowerQuery))
  )
}

export function getRelatedTools(toolSlug: string): Tool[] {
  const tool = getToolBySlug(toolSlug)
  if (!tool) return []

  return tool.relatedTools
    .map(slug => getToolBySlug(slug))
    .filter((t): t is Tool => t !== undefined)
    .slice(0, 5)
}

export const featuredTools = allTools.filter(tool => tool.featured)

export const toolsByCategory: Record<ToolCategory, Tool[]> = {
  [ToolCategory.FILE]: getToolsByCategory(ToolCategory.FILE),
  [ToolCategory.IMAGE]: getToolsByCategory(ToolCategory.IMAGE),
  [ToolCategory.TEXT]: getToolsByCategory(ToolCategory.TEXT),
  [ToolCategory.CODE]: getToolsByCategory(ToolCategory.CODE),
  [ToolCategory.SEO]: getToolsByCategory(ToolCategory.SEO),
  [ToolCategory.VIDEO]: getToolsByCategory(ToolCategory.VIDEO),
  [ToolCategory.AUDIO]: getToolsByCategory(ToolCategory.AUDIO),
  [ToolCategory.SECURITY]: getToolsByCategory(ToolCategory.SECURITY),
}
